### PR TITLE
Allows user to experience looped version of app

### PR DESCRIPTION
**Pull request by rubybaby**
- app.rb: put a loop around entire code

### CODE REVIEW

**Comment by soumyaray** [comment]
gimme a day to examine what you have proposed...

**Comment by lockys** [comment]
:100:

**Comment by John-Lin** [comment]
I am on :tv: lol

**Comment by rubybaby** [comment]
take your time. notice added a `loop`

**Comment by hirakujira** [comment]
=͟͟͞͞( •̀д•́)))  =͟͟͞͞( •̀д•́)))

**Comment by John-Lin** [comment]
Please consider to merge #3 :)

**Pull request merged**
